### ISSUE TITLE
Unhandled error for ".note <nonexistent note>"

### ISSUE THREAD

**Issue by JohnMaguire** [JohnMaguire/Cardinal#49]
```
2015-04-27 00:26:25,770 - cardinal.plugins - INFO - Calling callbacks for event: irc.privmsg
Unhandled Error
Traceback (most recent call last):
  File "/home/john/files/Cardinal-DH/local/lib/python2.7/site-packages/twisted/protocols/policies.py", line 120, in dataReceived
    self.wrappedProtocol.dataReceived(data)
  File "/home/john/files/Cardinal-DH/local/lib/python2.7/site-packages/twisted/words/protocols/irc.py", line 2430, in dataReceived
    basic.LineReceiver.dataReceived(self, data.replace('\r', ''))
  File "/home/john/files/Cardinal-DH/local/lib/python2.7/site-packages/twisted/protocols/basic.py", line 571, in dataReceived
    why = self.lineReceived(line)
  File "/home/john/files/Cardinal-DH/local/lib/python2.7/site-packages/twisted/words/protocols/irc.py", line 2438, in lineReceived
    self.handleCommand(command, prefix, params)
--- <exception caught here> ---
  File "/home/john/files/Cardinal-DH/local/lib/python2.7/site-packages/twisted/words/protocols/irc.py", line 2482, in handleCommand
    method(prefix, params)
  File "/home/john/files/Cardinal-DH/cardinal/bot.py", line 144, in irc_PRIVMSG
    self.plugin_manager.call_command(user, channel, message)
  File "/home/john/files/Cardinal-DH/cardinal/plugins.py", line 630, in call_command
    command(self.cardinal, user, channel, message)
  File "/home/john/files/Cardinal-DH/plugins/notes/plugin.py", line 118, in get_note
    content = self._get_note_from_db(title)
  File "/home/john/files/Cardinal-DH/plugins/notes/plugin.py", line 134, in _get_note_from_db
    if not result[0]:
exceptions.TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by JohnMaguire** [comment]
Affects the join handler too:

```
2015-04-26 21:44:05,538 - cardinal.plugins - ERROR - Exception during callback LMK5OV for event: irc.join
Traceback (most recent call last):
  File "/home/john/files/Cardinal-DH/cardinal/plugins.py", line 807, in fire
    callback(self.cardinal, *params)
  File "/home/john/files/Cardinal-DH/plugins/notes/plugin.py", line 26, in join_callback
    content = self._get_note_from_db(user.group(1))
  File "/home/john/files/Cardinal-DH/plugins/notes/plugin.py", line 134, in _get_note_from_db
    if not result[0]:
TypeError: 'NoneType' object has no attribute '__getitem__'
```
