### ISSUE TITLE
YouTube plugin has issues with spaces???

### ISSUE THREAD

**Issue by Someguy123** [JohnMaguire/Cardinal#57]
E.g.

    .youtube litecoin

works great but

    .youtube litecoin association

note: some things with spaces work fine. above term breaks it, even though "litecoin association" returns results on youtube just fine.

causes an exception:

    2015-05-10 22:23:59,113 - cardinal.plugins - INFO - Calling callbacks for event: irc.privmsg
    Unhandled Error
    Traceback (most recent call last):
      File "/home/azureuser/.local/lib/python2.7/site-packages/twisted/protocols/policies.py", line 120, in dataReceived
        self.wrappedProtocol.dataReceived(data)
      File "/home/azureuser/.local/lib/python2.7/site-packages/twisted/words/protocols/irc.py", line 2430, in dataReceived
        basic.LineReceiver.dataReceived(self, data.replace('\r', ''))
      File "/home/azureuser/.local/lib/python2.7/site-packages/twisted/protocols/basic.py", line 571, in dataReceived
        why = self.lineReceived(line)
      File "/home/azureuser/.local/lib/python2.7/site-packages/twisted/words/protocols/irc.py", line 2438, in lineReceived
        self.handleCommand(command, prefix, params)
    --- <exception caught here> ---
      File "/home/azureuser/.local/lib/python2.7/site-packages/twisted/words/protocols/irc.py", line 2482, in handleCommand
        method(prefix, params)
      File "/home/azureuser/Cardinal/cardinal/bot.py", line 150, in irc_PRIVMSG
        self.plugin_manager.call_command(user, channel, message)
      File "/home/azureuser/Cardinal/cardinal/plugins.py", line 695, in call_command
        command(self.cardinal, user, channel, message)
      File "/home/azureuser/Cardinal/plugins/youtube/plugin.py", line 62, in search
        message = self._parse_item(result['items'][0])
      File "/home/azureuser/Cardinal/plugins/youtube/plugin.py", line 110, in _parse_item
        video_id = video_id['videoId']
    exceptions.KeyError: 'videoId'

**Comment by JohnMaguire** [comment]
Fixed. It was bringing up channels in search results, instead of just videos. :)
