### ISSUE TITLE
URL detection plugin tripping over some characters in Github URLs

### ISSUE THREAD

**Issue by JohnMaguire** [JohnMaguire/Cardinal#73]
```
2015-09-09 19:32:14,030 - cardinal.plugins - INFO - Calling callbacks for event: urls.detection
Unhandled Error
Traceback (most recent call last):
  File "/home/john/files/Cardinal-DH/local/lib/python2.7/site-packages/twisted/protocols/policies.py", line 120, in dataReceived
    self.wrappedProtocol.dataReceived(data)
  File "/home/john/files/Cardinal-DH/local/lib/python2.7/site-packages/twisted/words/protocols/irc.py", line 2430, in dataReceived
    basic.LineReceiver.dataReceived(self, data.replace('\r', ''))
  File "/home/john/files/Cardinal-DH/local/lib/python2.7/site-packages/twisted/protocols/basic.py", line 571, in dataReceived
    why = self.lineReceived(line)
  File "/home/john/files/Cardinal-DH/local/lib/python2.7/site-packages/twisted/words/protocols/irc.py", line 2438, in lineReceived
    self.handleCommand(command, prefix, params)
--- <exception caught here> ---
  File "/home/john/files/Cardinal-DH/local/lib/python2.7/site-packages/twisted/words/protocols/irc.py", line 2482, in handleCommand
    method(prefix, params)
  File "/home/john/files/Cardinal-DH/cardinal/bot.py", line 155, in irc_PRIVMSG
    self.plugin_manager.call_command(user, channel, message)
  File "/home/john/files/Cardinal-DH/cardinal/plugins.py", line 679, in call_command
    command(self.cardinal, user, channel, message)
  File "/home/john/files/Cardinal-DH/plugins/urls/plugin.py", line 99, in get_title
    title = str(h.unescape(title).encode('utf-8'))
exceptions.UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 19: ordinal not in range(128)
```

https://github.com/ipfs/ipfs/issues/38 (for example)

**Comment by JohnMaguire** [comment]
That line should probably become: `title = h.unescape(title).decode('ascii', 'replace').replace(u"\ufffd\ufffd", '?')`

I need to test it before I merge it in though..
